### ISSUE TITLE
PAK names do not have to be in uppercase

### ISSUE THREAD

**Issue by livid** [ByteOverlord/Watch_Quake2#1]
I followed the instructions for building the app. It said, `PAK names have to be uppercase (case sensitive)`. So I renamed the three files to:

- PAK0.PAK
- PAK1.PAK
- PAK2.PAK

But the app would not start and complain:

```
Sys_Error: Couldn't load pics/colormap.pcx
```

So I changed them back to:

- pak0.pak
- pak1.pak
- pak2.pak

And it worked!

<img width="1004" alt="Screenshot 2023-09-07 at 11 45 49 AM" src="https://github.com/ByteOverlord/Watch_Quake2/assets/11427/07922f7d-9403-431b-8e4f-90e6974a7d56">

**Comment by IdeaVoid** [comment]
This part looks to be remnants from the Quake 1 port that was not updated.
Guide is now updated.

Thank you!
