### ISSUE TITLE
Automatic shooting when the target is in sight?

### ISSUE THREAD

**Issue by Maksimka101** [ByteOverlord/Watch_Quake2#2]
I don't know is it possible or not. But if it is, it would turn this project into a really playable game!

As an alternative, I can turn on the auto fire and use cheat to get all weapons every few minutes. But it's not convenient and unfair :(

Btw, thank you for this project. It's cool

**Comment by IdeaVoid** [comment]
This would be a nice feature to have.  

At this moment we are not planning to dive in to this as it would require some complex changes to the engine's code.
